name: delta_markdown
version: 0.2.0

description: A library for converting between Delta and Markdown.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  charcode: ^1.2.0
  collection: ^1.15.0-nullsafety.4
  flutter_quill: ^1.1.0

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5
