name: delta_markdown
version: 0.8.0

description: A library for converting between Markdown and Delta of the
  package flutter_quill.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  args: ^2.4.2
  charcode: ^1.3.1
  collection: ^1.15.0
  flutter_quill: ^8.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.3
